# Generated by Django 4.2.10 on 2024-02-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
